org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official

# Habilita AndroidX (requerido para Compose y librer?as modernas)
android.useAndroidX=true
# Habilita la regeneraci?n de librer?as antiguas a AndroidX
android.enableJetifier=true
# Suprime el aviso de compileSdk no soportado para la versi?n 36
android.suppressUnsupportedCompileSdk=36

# Protocolos TLS para el proxy
systemProp.https.protocols=TLSv1.2,TLSv1.3